<?php

$pizzas = array(
    'Margherita' => array('ingredients' => 'Tomate, Mozzarella', 'price' => '7'),
    'Puglia' => array('ingredients' => 'Tomate, ail', 'price' => '7'),
    'Primavera ' => array('ingredients' => 'Tomate, mozzarella, jambon', 'price' => '8'),
    'Salame' => array('ingredients' => 'Tomate, mozzarella, salami', 'price' => '8'),
    'Veneziana ' => array('ingredients' => 'Tomate, mozzarella, oignons, parmesan', 'price' => '8'),
    'Al tonno' => array('ingredients' => 'Tomate, mozzarella, thon, oignons', 'price' => '8.50'),
    'Funhgi' => array('ingredients' => 'Tomate, mozzarella, jambon, champignons', 'price' => '8.50'),
    'Chorizo' => array('ingredients' => 'Tomate, mozzarella, chorizo', 'price' => '8.50'),
    'Napoletana' => array('ingredients' => 'Tomate, mozzarella, anchois, câpres, olives', 'price' => '8.50'),
    'Hawaï' => array('ingredients' => 'Tomate, mozzarella, jambon, ananas', 'price' => '8.50'),
    'Paolo' => array('ingredients' => 'Tomate, mozzarella, lardons, oignons', 'price' => '9'),
    'Antonio' => array('ingredients' => 'Tomate, mozzarella, chèvre, miel', 'price' => '9'),
    'Capriciosa' => array('ingredients' => 'Tomate, mozzarella, jambon, champignons, artichauts, poivrons', 'price' => '10'),
    '4 Stagioni' => array('ingredients' => 'Tomate, mozzarella, jambon, champignons, artichauts, olives', 'price' => '10'),
    '4 Formaggi' => array('ingredients' => 'Tomate, mozzarella, parmesan, taleggio, gorgonzola', 'price' => '10'),
    'Parme' => array('ingredients' => 'Tomate, mozzarella, jambon de parme', 'price' => '10'),
    'Parmigiana' => array('ingredients' => 'Tomate, mozzarella, aubergines, parmesan', 'price' => '12'),
    'Scampi' => array('ingredients' => 'Tomate, mozzarella, scampi, ail', 'price' => '13'),
    'Fruitti di mare' => array('ingredients' => 'Tomate, mozzarella, fruit de mer, ail', 'price' => '13'),
    'Parme et rucola' => array('ingredients' => 'Tomate, mozzarella, jambon de parme, roquette, cp de parmesan, tomates cerises', 'price' => '13'),
    'Fabrizio' => array('ingredients' => 'Tomate, mozzarella, asperges, cp de parmesan, roquette, huile de trufle', 'price' => '13'),
    'Salsiccia' => array('ingredients' => 'Tomate, mozzarella, saucisses italiennes, piments frais', 'price' => '13'),
    'Nutella' => array('ingredients' => 'Nutella', 'price' => '10'),
    'Nutella bananes' => array('ingredients' => 'Nutella, Bananes', 'price' => '11'),
);
